export type Language = "en" | "ms";

export const translations = {
  en: { enter: "Enter", enterWebsite: "Enter Website", welcome: "Welcome", home: "Home", rsvp: "RSVP", events: "Events", contact: "Contact", doa: "Doa", sendMessage: "Send Message", gallery: "Gallery", story: "Our Story", travel: "Travel", faq: "FAQ", registry: "Registry", guestLogin: "Guest Sign In", username: "Username", language: "Language", countdown: "Countdown", days: "Days", hours: "Hours", minutes: "Minutes", seconds: "Seconds", accept: "Accept", decline: "Decline", accepted: "Accepted", declined: "Declined", pending: "Pending", rsvpStatus: "RSVP Status", eventDetails: "Event Details", date: "Date", time: "Time", venue: "Venue", address: "Address", dressCode: "Dress Code", programme: "Programme", notes: "Notes", yourName: "Your Name", yourMessage: "Your Message", submit: "Submit", messageSent: "Message sent successfully!", messageSentDesc: "Thank you for your well wishes.", charactersRemaining: "characters remaining", guestName: "Guest Name", wellWishes: "Well Wishes", selectLanguage: "Select Language", english: "English", bahasaMelayu: "Bahasa Melayu", backToHome: "Back to Home", youAreInvited: "You are invited", kindlyRespond: "Kindly respond", respondBy: "Please respond by", viewDetails: "View Details", close: "Close", loading: "Loading...", error: "Something went wrong", notInvited: "You are not invited to this event", noEvents: "No events available", poweredBy: "Powered by", invitation: "Invitation", bismillah: "In the name of Allah, the Most Gracious, the Most Merciful", inviteMessage: "With the blessing of Allah, we cordially invite you to share our joy on this blessed occasion", closingDua: "May Allah bless our union and grant us a lifetime of happiness" },
  ms: { enter: "Masuk", enterWebsite: "Masuk Laman Web", welcome: "Selamat Datang", home: "Utama", rsvp: "RSVP", events: "Acara", contact: "Hubungi", doa: "Doa", sendMessage: "Hantar Mesej", gallery: "Galeri", story: "Kisah Kami", travel: "Pelancongan", faq: "FAQ", registry: "Registry", guestLogin: "Daftar Masuk Tetamu", username: "Nama Pengguna", language: "Bahasa", countdown: "Kiraan", days: "Hari", hours: "Jam", minutes: "Minit", seconds: "Saat", accept: "Terima", decline: "Tolak", accepted: "Diterima", declined: "Ditolak", pending: "Menunggu", rsvpStatus: "Status RSVP", eventDetails: "Butiran Acara", date: "Tarikh", time: "Masa", venue: "Tempat", address: "Alamat", dressCode: "Pakaian", programme: "Program", notes: "Nota", yourName: "Nama Anda", yourMessage: "Mesej Anda", submit: "Hantar", messageSent: "Mesej berjaya dihantar!", messageSentDesc: "Terima kasih atas ucapan doa anda.", charactersRemaining: "aksara lagi", guestName: "Nama Tetamu", wellWishes: "Ucapan", selectLanguage: "Pilih Bahasa", english: "English", bahasaMelayu: "Bahasa Melayu", backToHome: "Kembali ke Utama", youAreInvited: "Anda dijemput", kindlyRespond: "Sila maklum balas", respondBy: "Sila maklum balas sebelum", viewDetails: "Lihat Butiran", close: "Tutup", loading: "Memuatkan...", error: "Sesuatu tidak kena", notInvited: "Anda tidak dijemput ke acara ini", noEvents: "Tiada acara tersedia", poweredBy: "Dikuasakan oleh", invitation: "Jemputan", bismillah: "Dengan nama Allah, Yang Maha Pemurah, Yang Maha Penyayang", inviteMessage: "Dengan rahmat Allah, kami menjemput anda untuk berkongsi kegembiraan kami pada majlis yang diberkati ini", closingDua: "Semoga Allah memberkati perkahwinan kami dan memberikan kami kebahagiaan sepanjang hayat" },
} as const;

export type TranslationKey = keyof typeof translations.en;

export function t(lang: Language, key: TranslationKey): string {
  return translations[lang][key] || translations.en[key] || key;
}
