import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
export function cn(...inputs: ClassValue[]) { return twMerge(clsx(inputs)); }
export function formatDate(date: string | null): string { if (!date) return ""; const d = new Date(date); if (isNaN(d.getTime())) return ""; return d.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" }); }
export function formatDateShort(date: string | null): string { if (!date) return ""; const d = new Date(date); if (isNaN(d.getTime())) return ""; return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }); }
export function formatTime(time: string | null): string { if (!time) return ""; const [h, m] = time.split(":"); const hour = parseInt(h, 10); const ampm = hour >= 12 ? "PM" : "AM"; return `${hour % 12 || 12}:${m} ${ampm}`; }
export function getCountdown(targetDate: string | null) { if (!targetDate) return { days: 0, hours: 0, minutes: 0, seconds: 0, isPast: true }; const target = new Date(targetDate).getTime(); const diff = target - Date.now(); if (diff <= 0) return { days: 0, hours: 0, minutes: 0, seconds: 0, isPast: true }; return { days: Math.floor(diff / 86400000), hours: Math.floor((diff % 86400000) / 3600000), minutes: Math.floor((diff % 3600000) / 60000), seconds: Math.floor((diff % 60000) / 1000), isPast: false }; }
export function debounce<T extends (...args: any[]) => void>(fn: T, delay: number) { let timer: ReturnType<typeof setTimeout>; return (...args: Parameters<T>) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), delay); }; }
export function isRsvpClosed(deadline: string | null): boolean { if (!deadline) return false; const d = new Date(deadline); if (isNaN(d.getTime())) return false; return Date.now() >= d.getTime(); }
export function getRsvpStatus(deadline: string | null): "open" | "closing-soon" | "closed" | "no-deadline" { if (!deadline) return "no-deadline"; const d = new Date(deadline); if (isNaN(d.getTime())) return "no-deadline"; const diff = d.getTime() - Date.now(); if (diff <= 0) return "closed"; if (diff <= 86400000) return "closing-soon"; return "open"; }
export function formatDeadline(deadline: string | null): string { if (!deadline) return ""; const d = new Date(deadline); if (isNaN(d.getTime())) return ""; return d.toLocaleString("en-US", { dateStyle: "long", timeStyle: "short" }); }
export function toDatetimeLocal(dateStr: string | null): string { if (!dateStr) return ""; const d = new Date(dateStr); if (isNaN(d.getTime())) return ""; const offset = d.getTimezoneOffset() * 60000; return new Date(d.getTime() - offset).toISOString().slice(0, 16); }
export function fromDatetimeLocal(localStr: string): string { if (!localStr) return ""; const d = new Date(localStr); if (isNaN(d.getTime())) return ""; return d.toISOString(); }
