/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WSlugRouteImport } from './routes/w.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as WSlugIndexRouteImport } from './routes/w.$slug.index'
import { Route as WSlugSigninRouteImport } from './routes/w.$slug.signin'
import { Route as WSlugInvitationRouteImport } from './routes/w.$slug.invitation'
import { Route as WSlugInfoRouteImport } from './routes/w.$slug.info'
import { Route as WSlugEventsRouteImport } from './routes/w.$slug.events'
import { Route as AuthenticatedManageSlugRouteImport } from './routes/_authenticated/manage.$slug'
import { Route as WSlugPPageSlugRouteImport } from './routes/w.$slug.p.$pageSlug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const WSlugIndexRoute = WSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugSigninRoute = WSlugSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugInvitationRoute = WSlugInvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugInfoRoute = WSlugInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugEventsRoute = WSlugEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => WSlugRoute,
} as any)
const AuthenticatedManageSlugRoute = AuthenticatedManageSlugRouteImport.update({
  id: '/manage/$slug',
  path: '/manage/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const WSlugPPageSlugRoute = WSlugPPageSlugRouteImport.update({
  id: '/p/$pageSlug',
  path: '/p/$pageSlug',
  getParentRoute: () => WSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/manage/$slug': typeof AuthenticatedManageSlugRoute
  '/w/$slug/events': typeof WSlugEventsRoute
  '/w/$slug/info': typeof WSlugInfoRoute
  '/w/$slug/invitation': typeof WSlugInvitationRoute
  '/w/$slug/signin': typeof WSlugSigninRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/w/$slug/p/$pageSlug': typeof WSlugPPageSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/manage/$slug': typeof AuthenticatedManageSlugRoute
  '/w/$slug/events': typeof WSlugEventsRoute
  '/w/$slug/info': typeof WSlugInfoRoute
  '/w/$slug/invitation': typeof WSlugInvitationRoute
  '/w/$slug/signin': typeof WSlugSigninRoute
  '/w/$slug': typeof WSlugIndexRoute
  '/w/$slug/p/$pageSlug': typeof WSlugPPageSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/_authenticated/manage/$slug': typeof AuthenticatedManageSlugRoute
  '/w/$slug/events': typeof WSlugEventsRoute
  '/w/$slug/info': typeof WSlugInfoRoute
  '/w/$slug/invitation': typeof WSlugInvitationRoute
  '/w/$slug/signin': typeof WSlugSigninRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/w/$slug/p/$pageSlug': typeof WSlugPPageSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/w/$slug'
    | '/manage/$slug'
    | '/w/$slug/events'
    | '/w/$slug/info'
    | '/w/$slug/invitation'
    | '/w/$slug/signin'
    | '/w/$slug/'
    | '/w/$slug/p/$pageSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/manage/$slug'
    | '/w/$slug/events'
    | '/w/$slug/info'
    | '/w/$slug/invitation'
    | '/w/$slug/signin'
    | '/w/$slug'
    | '/w/$slug/p/$pageSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/w/$slug'
    | '/_authenticated/manage/$slug'
    | '/w/$slug/events'
    | '/w/$slug/info'
    | '/w/$slug/invitation'
    | '/w/$slug/signin'
    | '/w/$slug/'
    | '/w/$slug/p/$pageSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  WSlugRoute: typeof WSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/w/$slug/': {
      id: '/w/$slug/'
      path: '/'
      fullPath: '/w/$slug/'
      preLoaderRoute: typeof WSlugIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/signin': {
      id: '/w/$slug/signin'
      path: '/signin'
      fullPath: '/w/$slug/signin'
      preLoaderRoute: typeof WSlugSigninRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/invitation': {
      id: '/w/$slug/invitation'
      path: '/invitation'
      fullPath: '/w/$slug/invitation'
      preLoaderRoute: typeof WSlugInvitationRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/info': {
      id: '/w/$slug/info'
      path: '/info'
      fullPath: '/w/$slug/info'
      preLoaderRoute: typeof WSlugInfoRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/events': {
      id: '/w/$slug/events'
      path: '/events'
      fullPath: '/w/$slug/events'
      preLoaderRoute: typeof WSlugEventsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/_authenticated/manage/$slug': {
      id: '/_authenticated/manage/$slug'
      path: '/manage/$slug'
      fullPath: '/manage/$slug'
      preLoaderRoute: typeof AuthenticatedManageSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/w/$slug/p/$pageSlug': {
      id: '/w/$slug/p/$pageSlug'
      path: '/p/$pageSlug'
      fullPath: '/w/$slug/p/$pageSlug'
      preLoaderRoute: typeof WSlugPPageSlugRouteImport
      parentRoute: typeof WSlugRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedManageSlugRoute: typeof AuthenticatedManageSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedManageSlugRoute: AuthenticatedManageSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface WSlugRouteChildren {
  WSlugEventsRoute: typeof WSlugEventsRoute
  WSlugInfoRoute: typeof WSlugInfoRoute
  WSlugInvitationRoute: typeof WSlugInvitationRoute
  WSlugSigninRoute: typeof WSlugSigninRoute
  WSlugIndexRoute: typeof WSlugIndexRoute
  WSlugPPageSlugRoute: typeof WSlugPPageSlugRoute
}

const WSlugRouteChildren: WSlugRouteChildren = {
  WSlugEventsRoute: WSlugEventsRoute,
  WSlugInfoRoute: WSlugInfoRoute,
  WSlugInvitationRoute: WSlugInvitationRoute,
  WSlugSigninRoute: WSlugSigninRoute,
  WSlugIndexRoute: WSlugIndexRoute,
  WSlugPPageSlugRoute: WSlugPPageSlugRoute,
}

const WSlugRouteWithChildren = WSlugRoute._addFileChildren(WSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  WSlugRoute: WSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
